"""Seed data mirrored from src/data/content.ts. Run once on server startup."""

SEED: dict = {
    "profile": {
        "name": "Muhammad Naufal Aulia",
        "initials": "MNA",
        "role": "Web Development & Digital Content",
        "location": "Banyuwangi, ID",
        "email": "novalqwerty15@gmail.com",
        "phone": "089515758977",
        "tagline": "keep minimalism.",
        "bio": "Software Engineering student at the intersection of technology and creativity — from simple web systems to visual stories. 50+ visual assets, 30+ tourism videos, live broadcast data for national events. Exploring data and AI.",
        "status": "Open for freelance",
        "socials": [
            {"label": "GitHub", "href": "https://github.com/mhmmd-naufl"},
            {"label": "LinkedIn", "href": "https://linkedin.com/in/mhmmd-naufl"},
            {"label": "Behance", "href": "https://behance.net/mhmmdnaufl"},
            {"label": "Instagram", "href": "https://instagram.com/mhmmd.naufl"},
        ],
    },
    "projects": [
        {
            "id": "P.01",
            "title": "Social Search App",
            "category": "Web — Analytics",
            "year": "2025",
            "stack": ["FastAPI", "Python", "Selenium"],
            "summary": "Backend FastAPI + scraping Selenium, dashboard web lokal analisis konten medsos (magang Kominfo).",
        },
        {
            "id": "P.02",
            "title": "Live Race Graphics",
            "category": "Broadcast — Data",
            "year": "2025",
            "stack": ["OBS", "Live Graphics"],
            "summary": "Grafik data + profil rute live Tour de Banyuwangi Ijen 2025.",
        },
        {
            "id": "P.03",
            "title": "Howheal Fun Run",
            "category": "Campaign — Social",
            "year": "2025",
            "stack": ["Figma", "CapCut"],
            "summary": "Kampanye fun run 100+ peserta, dari konsep hingga konten.",
        },
        {
            "id": "P.04",
            "title": "Tourism Recaps",
            "category": "Video — Tourism",
            "year": "2024",
            "stack": ["CapCut"],
            "summary": "30+ cinematic recap pariwisata Banyuwangi.",
        },
        {
            "id": "P.05",
            "title": "UMKM Brand Kit",
            "category": "Branding",
            "year": "2024",
            "stack": ["Figma", "Illustrator"],
            "summary": "Logo + flyer + instastory untuk klien lokal.",
        },
        {
            "id": "P.06",
            "title": "BIB Reader",
            "category": "CV — YOLOv8",
            "year": "2025",
            "stack": ["YOLOv8", "Python"],
            "summary": "Race BIB reader (proyek internal Alzen — detail menunggu izin publish).",
        },
    ],
    "capabilities": [
        {
            "no": "01",
            "title": "IT",
            "desc": "Backend FastAPI + scraping Selenium (Social Search), YOLOv8 (BIB reader), dokumentasi teknis.",
        },
        {
            "no": "02",
            "title": "Creative",
            "desc": "Desain minimalis, visual branding, video pendek, live broadcast multi-camera.",
        },
        {
            "no": "03",
            "title": "Analytics",
            "desc": "Analisis konten (Social Search), timing & scoring event, strategi konten. Data Science cert.",
        },
    ],
    "experiences": [
        {"period": "Jul 2025 — now", "role": "Software Engineer (intern)", "org": "Alzen Metro Data"},
        {"period": "Jul 2025 — Feb 2026", "role": "Broadcast Data & Camera", "org": "Alzen Metro Data"},
        {"period": "Feb — Jun 2025", "role": "Independent Intern (Social Search)", "org": "Kominfo Banyuwangi"},
        {"period": "Sep 2024 — Dec 2025", "role": "Social Media Specialist", "org": "Howheal.sac"},
        {"period": "Jun 2023 — Jun 2024", "role": "Content Creator", "org": "Visitbanyuwangi.id"},
        {"period": "Jan 2024 — now", "role": "Freelance Designer & Video Editor", "org": "Self Employed"},
    ],
    "certifications": [
        "BNSP Junior Mobile Programmer",
        "Data Science (Fresh Graduate Academy)",
        "Intro to Data Analytics",
        "Belajar Dasar Pemrograman Web",
        "EF SET 65/100 (C1)",
    ],
    "education": {
        "school": "Politeknik Negeri Banyuwangi",
        "degree": "D4 Teknologi Rekayasa Perangkat Lunak",
        "gpa": "3.63/4.00",
        "period": "2022 — 2026",
    },
}
